
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkShop.Xncf.Message.Models.DatabaseModel;

namespace WorkShop.Xncf.Message.Migrations.Migrations.SQLite
{
    [DbContext(typeof(MessageSenparcEntities))]
    partial class MessageSenparcEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");
#pragma warning restore 612, 618
        }
    }
}
